version: '3'
services:
  lobster:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./apps:/apps
      - ./requirements:/apps/requirements
    stdin_open: true
    tty: true
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: arm64v8/postgres:16
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - ./init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_USER=postgres
      - BISKIT_USER=${BISKIT_USER}
      - BISKIT_USER_PW=${BISKIT_USER_PW}
      - POSTGRES_DB=${POSTGRES_DB}ㅣㅣ
    ports:
      - "5432:5432"

volumes:
  app-db-data: