#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $BISKIT_USER WITH PASSWORD '$BISKIT_USER_PW';
    CREATE DATABASE $DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $BISKIT_USER TO $BISKIT_USER;
EOSQL
