#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $BISKIT_USER WITH PASSWORD '$BISKIT_USER_PW';
    CREATE DATABASE $DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $BISKIT_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $BISKIT_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $BISKIT_USER;
EOSQL
